theme: jekyll-theme-minimal
Description: This will go over the installation of Docker through the inital use of Ubuntu and then through a different number of options in regards for the project.

# Comments and Complaints marked by #
# Again, this is for installing on an Ubuntu Server terminal

1. sudo apt update # The first command from here

2. sudo apt install ca-certificates curl gnupg lsb-release

3. curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

4. echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
         https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/nul

5. sudo apt update

6. sudo apt install docker-ce docker-ce-cli containerd.io

7. sudo usermod -aG docker admin  # Last step but an issue I had at first was the "admin" input, replace "admin" with your username that you use for Ubuntu

# 7 is the last command for installing on an Ubuntu Server

# From here we install Docker Compose;
# Since we will assume that we didn't choose the Windows/Mac version the steps are that follows for Linux

1. sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

2. sudo chmod +x /usr/local/bin/docker-compose

# You should now be able to test and see if compose is available using the command: docker-compose --version

For this situation I choose Lab 2 Option B - WordPress Server. [Website(s) used https://upcloud.com/community/tutorials/wordpress-with-docker/]

1. Install Docker (Instructions above); Make sure to have curl command line utility (curl -V)
   Should be preinstalled for most Linux distributions, but if not, use sudo apt-get install curl (For Debian and Ubuntu)

2. Pre-install MariaDB for a relational database management system (replacement for MySQL)
   A) Input command mkdir ~/wordpress && cd ~/wordpress # To store files
   B) docker run -e MYSQL_ROOT_PASSWORD=<password> -e MYSQL_DATABASE=wordpress --name wordpressdb -v "$PWD/database":/var/lib/mysql -d mariadb:latest
      # B)'s Command Is based on setting up the enviornment of MariaDB, replace <password> with your own password
   C) Confirm that the MariaDB container is working correctly with the command [docker ps]
   D) Now install WordPress with Docker using the command [docker pull wordpress]
   



